### ISSUE TITLE
Allow for Jku endpoint setting on signer

### ISSUE THREAD

**Issue by Timunas** [TrueLayer/truelayer-signing#78]
## Motivations

I was trying to replicate a webhook call from truelayer to one endpoint and one of the steps on the webhook consumption as per suggested and using the `tlsigning.ExtractJwsHeader()`, the Jku endpoint is being validated as well as the signature by calling `tlsigning.VerifyWithJwks`.
For the signature bit I was using a mockserver to serve the JWKs, everything works well on signature validation however since it is not possible to set the Jku on the signer it is empty after calling `ExtractJwsHeader`, and I needed to disable the JKU endpoint validation because it won't match the mockserver expected one.
Having this possibility would allow us to use your library for both signing and validating the webhooks.

## Solution

I would like to be able to set the JKU endpoint on the signer.

## Additional context

I have tested this using golang lib.

**Comment by alexheretic** [comment]
Thanks for raising this. We actually do have this [in the rust lib](https://github.com/TrueLayer/truelayer-signing/blob/main/rust/src/sign.rs#L137) and indeed this is what our webhook logic is using. It wasn't added to the other langs because it isn't necessary for regular signing.

With the test case you describe in mind it makes sense to add this to our other lang implementations, with appropriate docs that state this is for webhook signing only. It also sounds like we can solve your issue in particular by adding to golang (cc @tl-marco-tormento).

**Comment by tl-marco-tormento** [comment]
Hey @Timunas, starting from version 0.1.6 of the golang lib you can now set the `jku` on the `Signer`.
